export const BUSINESS_REQUEST = 'BUSINESS_REQUEST'
export const BUSINESS_SUCCESS = 'BUSINESS_SUCCESS'
export const BUSINESS_FALIURE = 'BUSINESS_FALIURE'

export const KYC_REQUEST = 'KYC_REQUEST'
export const KYC_SUCCESS = 'KYC_SUCCESS'
export const KYC_FALIURE = 'KYC_FALIURE'