export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_FALIURE = 'NOTIFICATION_FALIURE'
//MARK NOTIFICATION
export const MARK_NOTIFICATION_REQUEST = 'MARK_NOTIFICATION_REQUEST'
export const MARK_NOTIFICATION_SUCCESS = 'MARK_NOTIFICATION_SUCCESS'
export const MARK_NOTIFICATION_FALIURE = 'MARK_NOTIFICATION_FALIURE'