export const SETPIN_REQUEST = 'SETPIN_REQUEST'
export const SETPIN_SUCCESS = 'SETPIN_SUCCESS'
export const SETPIN_FALIURE = 'SETPIN_FALIURE'
//

//
export const CHANGEPIN_REQUEST = 'CHANGEPIN_REQUEST'
export const CHANGEPIN_SUCCESS = 'CHANGEPIN_SUCCESS'
export const CHANGEPIN_FALIURE = 'CHANGEPIN_FALIURE'