//FOR BANK 
export const BANK_REQUEST = 'BANK_REQUEST'
export const BANK_SUCCESS = 'BANK_SUCCESS'
export const BANK_FALIURE = 'BANK_FALIURE'

//FOR ACCOUNT NAME
export const NAME_REQUEST = 'NAME_REQUEST'
export const NAME_SUCCESS = 'NAME_SUCCESS'
export const NAME_FALIURE = 'NAME_FALIURE'

//FOR TRANSER
export const TRANSFER_REQUEST = 'TRANSFER_REQUEST'
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS'
export const TRANSFER_FALIURE = 'TRANSFER_FALIURE'

export const  TRANSFER_DATA_REQUEST = 'TRANSFER_DATA_REQUEST'