export const DIRECTOR_REQUEST = 'DIRECTOR_REQUEST'
export const DIRECTOR_SUCCESS = 'DIRECTOR_SUCCESS'
export const DIRECTOR_FALIURE = 'DIRECTOR_FALIURE'

export const GET_DIRECTOR_REQUEST = 'GET_DIRECTOR_REQUEST'
export const GET_DIRECTOR_SUCCESS = 'GET_DIRECTOR_SUCCESS'
export const GET_DIRECTOR_FALIURE = 'GET_DIRECTOR_FALIURE'

